### ISSUE TITLE
Ошибка записи в закрытый канал

### ISSUE THREAD

**Issue by kutuluk** [kutuluk/unbubblable#1]
```2017/04/14 00:41:13 [ws read]: websocket: close 1001 (going away)
2017/04/14 00:41:13 [connect]: подключение с адреса [::1]:65052 завершено
2017/04/14 00:41:13 [connect]: ресивер завершился
2017/04/14 00:41:13 [player]: 1129 - не получено сообщение контроллера
panic: send on closed channel

goroutine 5 [running]:
github.com/kutuluk/unbubblable/server/connect.(*Connect).sendMessage(0xc042428000, 0xc000000002, 0xc042264ab0, 0xd, 0x10)
        C:/Gopath/src/github.com/kutuluk/unbubblable/server/connect/send.go:82 +0x1cd
github.com/kutuluk/unbubblable/server/connect.(*Connect).SendMovement(0xc042428000)
        C:/Gopath/src/github.com/kutuluk/unbubblable/server/connect/send.go:194 +0x374
github.com/kutuluk/unbubblable/server/connect.(*Hub).Tick(0xc0422196c0, 0x469)
        C:/Gopath/src/github.com/kutuluk/unbubblable/server/connect/hub.go:79 +0xb9
github.com/kutuluk/unbubblable/server/loop.(*Loop).Entry(0xc0420105a0)
        C:/Gopath/src/github.com/kutuluk/unbubblable/server/loop/loop.go:53 +0x132
created by github.com/kutuluk/unbubblable/server/loop.NewLoop
        C:/Gopath/src/github.com/kutuluk/unbubblable/server/loop/loop.go:38 +0x13e
```
ошибка возникает из-за того, что соединение закрывается после того, как коннект уже начинает обрабатываться в тикере - тогда ридер завершается, удаляет коннект из списка и закрывает канал райтера, но в тикере этот коннект еще в обработке и пытается писать в закрытый канал.

**Comment by kutuluk** [comment]
Ошибка исчезла после наведения порядка в ендере/ресивере.
